# Generated by Django 5.1.6 on 2025-03-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
