# Generated by Django 5.1.6 on 2025-03-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0005_alter_category_options_remove_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название Категории'),
        ),
    ]
