# Generated by Django 5.1.6 on 2025-04-01 11:58

import django.db.models.deletion
import olx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=olx.models.Product.get_default_subcategory, on_delete=django.db.models.deletion.CASCADE, to='olx.subcategory', verbose_name='Категория'),
        ),
    ]
