# Generated by Django 5.1.6 on 2025-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Местонахождение'),
        ),
    ]
