# Generated by Django 5.1.6 on 2025-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0009_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='None', max_length=100, verbose_name='Имя'),
        ),
    ]
