# Generated by Django 5.1.6 on 2025-04-04 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0013_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выпуска'),
        ),
    ]
