# Generated by Django 5.1.6 on 2025-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=2, upload_to='avatars/', verbose_name='Фото профиля'),
            preserve_default=False,
        ),
    ]
