# Generated by Django 5.1.6 on 2025-05-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0021_category_image_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]