# Generated by Django 5.1.6 on 2025-05-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0023_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photo_2/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photo_3/', verbose_name='Фото 3'),
        ),
    ]
