# Generated by Django 5.1.6 on 2025-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0024_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], default='new', max_length=10, verbose_name='Состояние'),
        ),
    ]
