# Generated by Django 5.1.6 on 2025-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0025_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Б/У', 'Б/У')], default='Новый', max_length=10, verbose_name='Состояние'),
        ),
    ]
